/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/cart': typeof CartRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/offers': typeof OffersRoute
  '/reservation': typeof ReservationRoute
  '/reviews': typeof ReviewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/cart': typeof CartRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/offers': typeof OffersRoute
  '/reservation': typeof ReservationRoute
  '/reviews': typeof ReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/cart': typeof CartRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/offers': typeof OffersRoute
  '/reservation': typeof ReservationRoute
  '/reviews': typeof ReviewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/branches'
    | '/cart'
    | '/gallery'
    | '/menu'
    | '/offers'
    | '/reservation'
    | '/reviews'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/branches'
    | '/cart'
    | '/gallery'
    | '/menu'
    | '/offers'
    | '/reservation'
    | '/reviews'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/branches'
    | '/cart'
    | '/gallery'
    | '/menu'
    | '/offers'
    | '/reservation'
    | '/reviews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BranchesRoute: typeof BranchesRoute
  CartRoute: typeof CartRoute
  GalleryRoute: typeof GalleryRoute
  MenuRoute: typeof MenuRoute
  OffersRoute: typeof OffersRoute
  ReservationRoute: typeof ReservationRoute
  ReviewsRoute: typeof ReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BranchesRoute: BranchesRoute,
  CartRoute: CartRoute,
  GalleryRoute: GalleryRoute,
  MenuRoute: MenuRoute,
  OffersRoute: OffersRoute,
  ReservationRoute: ReservationRoute,
  ReviewsRoute: ReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
